### ISSUE TITLE
Duplicate Target Scrapes on Prometheus - laa-apply-for-legal-aid-uat

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform-environments#1105]
We are getting a number of errors on Prometheus for Target duplicate scraps for laa-apply-for-legal-aid-uat.

level=warn ts=2019-08-14T12:09:16.705297979Z caller=scrape.go:1088 component="scrape manager" scrape_pool=laa-apply-for-legalaid-uat/apply-ap-831-prevent-changes-to-appl-monitor/0 target=http://100.96.14.252:9394/metrics msg="Error on ingesting out-of-order samples" num_dropped=47
level=warn ts=2019-08-14T12:09:18.811106275Z caller=scrape.go:1088 component="scrape manager" scrape_pool=laa-apply-for-legalaid-uat/apply-ap-804-print-application-monitor/0 target=http://100.96.37.230:9394/metrics msg="Error on ingesting out-of-order samples" num_dropped=94
level=warn ts=2019-08-14T12:09:18.814380824Z caller=scrape.go:1088 component="scrape manager" scrape_pool=laa-apply-for-legalaid-uat/apply-ap-831-prevent-changes-to-appl-monitor/0 target=http://100.96.37.230:9394/metrics msg="Error on ingesting out-of-order samples" num_dropped=94
level=warn ts=2019-08-14T12:09:18.815666397Z caller=scrape.go:1091 component="scrape manager" scrape_pool=laa-apply-for-legalaid-uat/apply-ap-707-html-errors-monitor/0 target=http://100.96.37.230:9394/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=1
level=warn ts=2019-08-14T12:09:26.482296787Z caller=scrape.go:1088 component="scrape manager" scrape_pool=laa-apply-for-legalaid-uat/apply-ap-799-domain-name-monitor/0 target=http://100.96.15.108:9394/metrics msg="Error on ingesting out-of-order samples" num_dropped=502
level=warn ts=2019-08-14T12:09:30.162576047Z caller=scrape.go:1091 component="scrape manager" scrape_pool=laa-apply-for-legalaid-uat/apply-ap-707-webhint-monitor/0 target=http://100.96.37.12:9394/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=1
level=warn ts=2019-08-14T12:09:33.858953135Z caller=scrape.go:1088 component="scrape manager" scrape_pool=laa-apply-for-legalaid-uat/apply-ap-799-domain-name-monitor/0 target=http://100.96.37.230:9394/metrics msg="Error on ingesting out-of-order samples" num_dropped=94

Looking at the Status > Targets tab on Prometheus, we can see 5 Targets setup for the UAT namespace, but they are all scraping the same 5 endpoints with the same labels causing the errors above. Prod and Staging do not have this issue as they have the one target scraping one endpoint.

**Comment by sablumiah** [comment]
There are now 2 targets scarping the same endpoints:

laa-apply-for-legalaid-uat/apply-ap-886-printing-monitor/0 
laa-apply-for-legalaid-uat/apply-ap-512-pages-monitor/0

**Comment by scruti** [comment]
Gave this a quick check. I'm not very familiar with Prometheus but by what I found in https://prometheus.cloud-platform.service.justice.gov.uk/targets#job-laa-apply-for-legalaid-uat%2fapply-ap-512-pages-monitor%2f0 seems they have different `job`, `pod` and `service` labels depending on the branch. Unless I got it wrong and all the different targets receive all the alerts for all the branches.

Will try to investigate it more and catch up with @Kalagan next week as he has better context on Prometheus configs.

**Comment by scruti** [comment]
Ended creating a ticket for this so we can formally address it instead of me coming back now and then to the issue trying to figure out how to avoid it while scratching my head before being pulled for a high priority action somewhere else:
To track it: https://dsdmoj.atlassian.net/browse/AP-967

**Comment by digitalronin** [comment]
@scruti Is there any ETA on when this might be fixed?

**Comment by scruti** [comment]
Apologies for the delay. We lost the developer who had better context on K8s/Prometheus and I had to onboard myself on the technology to try to fix it.

I think I managed to get a fix by setting unique labels per release for the Service Monitor, so will target the individual release/branch instead of everything released under the same namespace.

https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/1001


## Before/After

![image](https://user-images.githubusercontent.com/1227578/68148392-d268a880-ff33-11e9-857e-2a852ea88635.png)

Will merge it as soon as I doublecheck this doesn't break the expected Prometheus behaviour.

**Comment by scruti** [comment]
Fix merged. 
The alert will still show up until the current branches in UAT get rebased against master and released again or merged into master. But will eventually disappear completely.

Thanks everyone for the patience on this.

**Comment by scruti** [comment]
Issue fixed once all the branches have been refreshed.
