### ISSUE TITLE
Clean up old developer sandbox namespaces & ECRs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform-environments#477]
We probably have several namespaces in the cluster which developers created while learning how to use the cluster, but which are no longer required.

If we can identify namespaces which are no longer required, we could ask the relevant developer if they still need the namespace and, if they don't, we can delete it and any associated ECRs.

This will help to keep our concourse running time down, and this repo clean.

[This gist](https://gist.github.com/digitalronin/42daeb6a5f6272cf2258fce998808e10) might be useful as a way to quickly identify candidate namespaces to investigae.

**Comment by ermiasworku** [comment]
Hi,

Thanks for the info. I will try and clean up some of the works that is no longer required.

Thanks,

**Comment by ermiasworku** [comment]
we no longer need this namespace --> cica-apply-for-compensation-uat and cica-oas-basic-testing

Happy for this to be deleted.

**Comment by digitalronin** [comment]
@ermiasworku Please go through the procedure described [here](https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#cleaning-up) to delete these namespaces.
